# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ilitton.github.io
title: 
email: isabel.litton@gmail.com
author: Isabel Litton
description: > # Data scientist, Netflix marathoner, ice cream aficionado
copyright: 'Copyright &copy; 2015 iLitton. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/iLitton
  - title: github
    url: https://github.com/iLitton
  - title: linkedin
    url: https://www.linkedin.com/in/ilitton